Feat: files processing
pubky/pubky-nexus pull request #165
Opened 2024-10-15 09:36 UTC by amirRamirfatahi

# Pre-submission Checklist

> For tests to work you need a working neo4j and redis instance with the example dataset in `docker/db-graph`

- [ ] **Testing**: Implement and pass new tests for the new features/fixes, `cargo test`.
- [ ] **Performance**: Ensure new code has relevant performance benchmarks, `cargo bench`

2025-01-01 17:30 UTC, SHAcollision requested changes
TLDR: this PR needs your own detailed review, there is a lot of low hanging improvements that hint you have not gone over your PR before requesting the review: this leads to a waste of time for both.

Certainly needs:
- Rewrite `static_files_middleware` to make it readable. If possible, let's use Axum handlers and document this endpoint on swagger as well.
- Benchmarking is needed.
- Provide Clear Documentation & Comments
If `static_processor` has a variety of specialized logic (e.g., ImageMagick/FFmpeg commands, path manipulations, version enumerations, caching, etc.), make sure to:
1. Document each function with a short doc comment (///).
2. Explain why certain commands or transformations are used, especially if they involve system calls or external tools (ImageMagick, FFmpeg).
3. Clarify any assumptions about the environment (e.g., “We expect convert from ImageMagick to be installed.”). And of course: make it optional!
- Although tests exist, some scenarios require more robust checks:
Ensure tests handle invalid file versions (e.g., a request for a “nonexistent” variant).
Validate edge cases like large file sizes, unsupported content types, or corrupted data.

Overall a lot of simplification, better error handling, improved readability/maintainability, and stick to the conventions we use in the rest of the codebase is needed.

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/store.rs
> +    let file_path = format!("{}/{}", path, name);
Better use `PathBuf` and .join() to build paths reliably instead all those `format!("{}/{}/{}..."` ?

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/mod.rs
> +
`src/static_processor` is a new top level module with a bunch of miscellaneous utils. So much room to use Rust idiomatic for better maintainability and readability. 

ideas
```
pub trait MediaProcessor {
    fn create_variant(&self, version: FileVersion) -> Result<String, DynError>;
}

impl MediaProcessor for ImageDetails {
    fn create_variant(&self, version: FileVersion) -> Result<String, DynError> {
        // Implement image-specific logic
    }
}

impl MediaProcessor for VideoDetails {
    fn create_variant(&self, version: FileVersion) -> Result<String, DynError> {
        // Implement video-specific logic
    }
}
```

Please, document the new functions.

2025-01-01 17:30 UTC, SHAcollision commented on src/events/handlers/file.rs
> +    store_blob(String::from("main"), full_path.to_string(), &blob).await?;
Is `"main"` the "name" ? or the variant?, fix `store_blob()` signature.

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/video.rs
> +// }
?

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/video.rs
> +}
?

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/mod.rs
> +            .then_some(format!("{}/small", path)),
`".../small"`

You implemented the Display trait on `FileVersions` enum.

2025-01-01 17:30 UTC, SHAcollision commented on src/routes/static.rs
> +        format!("{}/main", request.uri().path())
you implemented Display on the FileVersions enum. Could be used here.

2025-01-01 17:30 UTC, SHAcollision commented on src/routes/static.rs
> +                return Err(StatusCode::INTERNAL_SERVER_ERROR);
Is this the best descriptive error we can throw here?

2025-01-01 17:30 UTC, SHAcollision commented on src/static_processor/image.rs
> +        "JPEG" => None,
If we are going to re-format, we could very well better use some WEBP compressed to ~80% quality

2025-01-01 20:06 UTC, SHAcollision commented on src/static_processor/video.rs
> +    }
Pretty weird construction here again. A `match` statement on the return of a function that calls an external process to later do a half-assed handling of the result. Can't you simply make sure `process_video` returns the correct error and raise with `process_video().await?`

2025-01-03 16:24 UTC, amirRamirfatahi commented on src/routes/static.rs
> +use std::borrow::BorrowMut;
what do you mean "??" :)) 
Had to import it because of `*request.uri_mut() = new_uri.parse().unwrap();`.  Both are removed.

2025-01-03 16:24 UTC, amirRamirfatahi commented on src/routes/static.rs
> +    *request.borrow_mut().uri_mut() = new_uri.parse().unwrap();
yes..

2025-01-03 16:27 UTC, amirRamirfatahi commented on src/routes/static.rs
> +    let path_parts: Vec<&str> = path.split("/").collect();
Will try the extractor now. previously couldn't because it didn't support it.

2025-01-03 16:28 UTC, amirRamirfatahi commented on src/routes/static.rs
> +    let version = if path_parts.len() == 6 {
this is a custom middleware for this one handler (possibly for a long time). I don't see how it can be a nightmare?!

2025-01-03 16:29 UTC, amirRamirfatahi commented on src/routes/static.rs
> +            Err(StatusCode::INTERNAL_SERVER_ERROR)
What do you mean "wasteful error management?!"

2025-01-03 16:29 UTC, amirRamirfatahi commented on src/static_processor/image.rs
> +        FileVersions::SMALL => String::from("320"),
resolution will be kept the same. that's why we only need a width.

2025-01-03 16:39 UTC, amirRamirfatahi commented on src/static_processor/image.rs
> +        "JPEG" => None,
It still doesn't have the availability of jpeg 
https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

2025-01-04 19:04 UTC, SHAcollision commented on src/static_processor/image.rs
> +        "JPEG" => None,
All of the assets of pubky-app frontend are WEBP. It's rare to find browsers that do not support WEBP. We should default to webp and only if there were issues (I guess not) do JPEG.

2025-01-06 18:34 UTC, SHAcollision commented on src/static_processor/middleware.rs
> +use reqwest::StatusCode;
We are building an **Axum** server, so we should stick to using Axum types.

Using `reqwest` client `StatusCode` type for our Axum response is sketchy. In addition, as soon as PubkyClient can perform requests to the `{homeserver_pubky_id}/events` we won't need `Reqwest` library anymore.

2025-01-24 10:41 UTC, tipogi commented on src/static_processor/processors/image.rs
> +                String::from_utf8_lossy(&child_output.stdout)
Maybe we should use `stderr` for more accurate error handling?

2025-01-24 10:41 UTC, tipogi commented on src/static_processor/processors/image.rs
> +            .arg("-resize")
Also maybe add `-strip` command to delete metadata?

2025-01-24 10:41 UTC, tipogi commented on src/static_processor/store.rs
> +        Ok(())
refactor

2025-01-24 10:41 UTC, tipogi commented on src/events/handlers/file.rs
In the `put` function, we usually convert the event to `pubky-app-specs` mdoel and then send that object to `sync_put`. We no longer use `ingest` name

2025-01-27 22:23 UTC, amirRamirfatahi commented on src/routes/static/files.rs
> +    };
I'm returning from the function which you can't do in a closure.  
The rest is also much more readable IMO.

2025-01-27 22:25 UTC, amirRamirfatahi commented on src/routes/static/files.rs
> +        StaticProcessor::get_content_type_for_variant(&file, &variant)
that was verification that a variant for a content_type exists.  
This is to get the new processed file content type.

2025-01-27 23:54 UTC, amirRamirfatahi commented on src/static_processor/processors/image.rs
> +            .arg("-resize")
I think this way is really cleaner.  
Not sure about deleting metadata though.

2025-01-27 23:55 UTC, amirRamirfatahi commented on src/static_processor/processors/image.rs
> +                String::from_utf8_lossy(&child_output.stdout)
`.output() // Automatically pipes stdout and stderr` is a couple lines up

2025-01-28 00:02 UTC, amirRamirfatahi commented on src/events/handlers/file.rs
this is already happening? `ingest` is another function.

2025-02-05 17:38 UTC, SHAcollision requested changes
I'm eager to merge this so we can tackle https://github.com/pubky/pubky-nexus/issues/319 but this PR is still very green IMO. @amirRamirfatahi why not focus on finishing pending PRs instead of opening more fronts (e.g. #314).

2025-02-05 17:38 UTC, SHAcollision commented on src/static_processor/processors/image.rs
> +}
Suggestion for simplification and use of `cwebp`
```suggestion
const SMALL_IMAGE_WIDTH: &str = "320";
const FEED_IMAGE_WIDTH: &str = "720";

pub struct ImageOptions {
    width: Option<String>,
    content_type: String,
}

impl BaseProcessingOptions for ImageOptions {
    fn content_type(&self) -> String {
        self.content_type.clone()
    }
}

pub struct ImageProcessor;

#[async_trait]
impl FileProcessor for ImageProcessor {
    type ProcessingOptions = ImageOptions;

    fn get_valid_variants_for_content_type(_content_type: &str) -> Vec<FileVariant> {
        // Always allow main, feed, small for images including gif.
        vec![FileVariant::Main, FileVariant::Small, FileVariant::Feed]
    }

    fn get_content_type_for_variant(_file: &FileDetails, _variant: &FileVariant) -> String {
        // We always convert to image/webp
        String::from("image/webp")
    }

    fn get_options_for_variant(
        file: &FileDetails,
        variant: &FileVariant,
    ) -> Result<ImageOptions, DynError> {
        // We always produce .webp
        let content_type = Self::get_content_type_for_variant(file, variant);
        let width = match variant {
            // For 'main', we won't resize. For feed/small, we specify widths.
            FileVariant::Main => None,
            FileVariant::Feed => Some(String::from(FEED_IMAGE_WIDTH)),
            FileVariant::Small => Some(String::from(SMALL_IMAGE_WIDTH)),
        };
        Ok(ImageOptions {
            width,
            content_type,
        })
    }

    async fn process(
        origin_file_path: &str,
        output_file_path: &str,
        options: &ImageOptions,
    ) -> Result<String, DynError> {
        // We will call cwebp to convert to .webp at 80% quality
        // If a width is specified, we do:  -resize <width> 0
        // Otherwise, no -resize argument => keeps original size
        //
        // We'll produce an output file without .webp in name to stay consistent
        // with how code references "main", "feed", "small". But the content is .webp.

        use tokio::process::Command;

        let mut cmd_args = vec!["-q", "80"];
        if let Some(ref w) = options.width {
            cmd_args.push("-resize");
            cmd_args.push(w);
            cmd_args.push("0");
        }
        cmd_args.push(origin_file_path);
        cmd_args.push("-o");
        cmd_args.push(output_file_path);

        let child_output = Command::new("cwebp").args(&cmd_args).output().await?;

        if !child_output.status.success() {
            let stderr = String::from_utf8_lossy(&child_output.stderr);
            return Err(format!("cwebp command failed: {}", stderr).into());
        }

        // Return final content_type
        Ok(options.content_type())
    }
}
```

2025-02-05 17:38 UTC, SHAcollision commented on .github/workflows/test.yml
> +        run: sudo apt install -y imagemagick
```suggestion
        run: sudo apt-get install -y webp
```

2025-02-05 17:38 UTC, SHAcollision commented on src/static_processor/processors/image.rs
> +            FileVariant::Feed => String::from(FEED_IMAGE_WIDTH),
Unresolve comment: what happens if a user uploads a 200x200 image, are we resizing it to 720?

2025-02-11 10:56 UTC, SHAcollision commented on src/routes/v0/user/avatar.rs
Yes, I think we should move the logic inside the avatar handler to a `UserAvatar::get_by_id()` . This will also be the function we can add to benchmarks.

2025-02-11 11:45 UTC, SHAcollision commented on src/events/handlers/file.rs
> +            StaticStorage::store_blob(FileVariant::Main.to_string(), full_path.to_string(), &blob)
Nice

2025-02-12 06:44 UTC, tipogi commented on src/routes/v0/user/avatar.rs
> +        .insert("content-type", content_type_header);
I think that one, we could refactor creating another static function in `StaticProcessor` that returns a response as a result. we have the same block in the `static_files_handler`. One option
```rust
pub async fn swap_serve_dir_and_add_content_type(
        request: Request<Body>,
        content_type: String,
        custom_uri: Option<String>
    ) -> Result<Response<ServeFileSystemResponseBody>, Error> {
        let (request_parts, request_body) = request.into_parts();
        let mut req = Request::from_parts(request_parts.clone(), request_body);
        let file_uri_path = match custom_uri {
            Some(new_uri) => new_uri,
            None => request_parts.uri.to_string()
        };
        *req.uri_mut() =
            file_uri_path
                .as_str()
                .parse::<Uri>()
                .map_err(|err| Error::InternalServerError {
                    source: Box::new(err),
                })?;
        let response_result = get_serve_dir().try_call(req).await;

        let mut response = match response_result {
            Ok(response) => {
                if response.status() != StatusCode::OK {
                    return Ok(response);
                }
                response
            }
            Err(err) => {
                return Err(Error::InternalServerError {
                    source: Box::new(err),
                });
            }
        };

        // set the content type header
        let content_type_header = content_type.parse().map_err(|err| {
            error!("Invalid content type header: {}", content_type);
            Error::InternalServerError {
                source: Box::new(err),
            }
        })?;
        response
            .headers_mut()
            .insert("content-type", content_type_header);
        Ok(response)
    }
```
    
That refactoring makes me think whether we should keep _SERVE_DIR_INSTANCE_ in `mod.rs`, or if we should create another file inside the static folder for all `ServeDir` related operations.

Like this, we could have:

```rust
struct xxx {
fn serve_static_dir_response() -> Res<Resp,xxx> // not 100% sure the name...
fn add_content_type(&response)
fn add_content_disposition(&response)
...
static SERVE_DIR_INSTANCE...
```

2025-02-13 09:07 UTC, tipogi approved these changes
From my side, clear and ready to merge 🚀

2025-02-18 13:11 UTC, SHAcollision approved these changes
Did not test myself, but looks good. Let's figure out next steps after merge.

2025-02-20 20:25 UTC, SHAcollision commented
@amirRamirfatahi  this PR gives me nightmares at night. Please merge.

2025-02-25 16:55 UTC, tipogi commented on src/routes/static/mod.rs
> +    router.nest_service(STATIC_ROUTE, get_service(ServeDir::new(config.static_path)))
could we use here, `PubkyServeDir::get_serve_dir()` instead of create a new _ServeDir_?

2025-04-01 23:31 UTC, SHAcollision commented
This PR was merged to `dev` and then `main`

2025-04-01 23:31 UTC, closed without merging