Add post_replies
pubky/pubky-nexus pull request #239
Opened 2024-12-05 12:48 UTC by amirRamirfatahi

This PR solves #228 
# Pre-submission Checklist

> For tests to work you need a working neo4j and redis instance with the example dataset in `docker/db-graph`

- [ ] **Testing**: Implement and pass new tests for the new features/fixes, `cargo test`.
- [ ] **Performance**: Ensure new code has relevant performance benchmarks, `cargo bench`

2025-01-02 08:06 UTC, SHAcollision requested changes
The PR looks good. There is a few things we can improve.

This PR still needs at least 1 more test and it would be very nice if we also add a benchmark for this new stream of users.

2025-01-02 08:06 UTC, SHAcollision commented on src/models/user/stream.rs
> +                Some(unique_user_ids.into_iter().collect())
Avoid `unwrap()`

Untested, maybe something like.
```
   let unique_user_ids: HashSet<String> = replies
        .map(|replies_batch| {
            replies_batch
                .into_iter()
                .filter_map(|(raw_id, _some_other_data)| {
                    // Split on ":" and take the first piece; avoid `unwrap()`
                    raw_id.split(':').next().map(ToString::to_string)
                })
                .collect::<Vec<String>>()
        })
        .flatten()
        .collect();

2025-01-02 08:06 UTC, SHAcollision commented on src/models/user/stream.rs
> +            }
Too much logic inside of this arm of the match statement. 

We should do the same as for the `UserStreamSource::Recommended` arm. Move the logic to the `get_post_replies_ids(post_id: &str, author_id: &str)` function.

2025-01-02 08:08 UTC, SHAcollision commented
> This PR solves #228

Please use the keyword `Fixes` as in `Fixes #228` to automatically link this PR to the issue.

2025-01-21 16:58 UTC, SHAcollision commented
Is this PR ready for review?

2025-02-11 17:20 UTC, SHAcollision reviewed
This PR is basically ready to merge I only left a few minor NIT comments that I think are worth adressing.

2025-02-11 17:20 UTC, SHAcollision commented on src/models/user/stream.rs
> +                            .split(":")
I'm not 100% sure on this one. I think `reply.0.split(":").map(ToString::to_string).collect::<Vec<String>>()[0].clone()` could potentially panic if the reply string does not contain a colon (I know, it should). But instead, we could consider using iterator methods like `.next()` with proper error handling.

2025-02-11 17:20 UTC, SHAcollision commented on src/models/user/stream.rs
> +        Ok(Some(unique_user_ids.into_iter().collect()))
NIT: There is a lot going on in the 2 last statements of this function. Maybe we can divide them into more lines for clarity.

NIT: It might be nice to document (small comment right here `//`) that we are using HashSet to enforce uniqueness, but the order of the repliers is not guaranteed. We could also sort the vector before returning (not worth it IMO, no requirement for ordering AFAIK).

2025-02-11 17:20 UTC, SHAcollision commented on src/models/user/stream.rs
> +        Ok(Some(unique_user_ids.into_iter().collect()))
Maybe something like this is clearer and panic safe.
```suggestion
        // If there are replies, extract unique user IDs using a HashSet.
        let unique_user_ids: HashSet<String> = if let Some(replies) = replies {
            replies
                .into_iter()
                .filter_map(|reply| reply.0.split(':').next().map(|s| s.to_string()))
                .collect()
        } else {
            // If no replies are found, return None.
            return Ok(None);
        };

        // Convert the HashSet to a Vec. (Note: the ordering will be arbitrary.)
        Ok(Some(unique_user_ids.into_iter().collect()))
```

2025-02-13 07:31 UTC, amirRamirfatahi commented on src/models/user/stream.rs
> +pub struct UserStreamInput {
I don't know about "not improving clarity". The `clippy` rule is clearly there because when the number of args increases, it becomes hard to track them, while the verbosity + unsorted nature of struct helps with dealing these cases. Let's keep the struct as it is. The `clippy` rule is strict as is with 7 args, meaning we probably won't have many of these cases.

2025-02-24 23:23 UTC, merged