Fix user search duplicate bug
pubky/pubky-nexus pull request #260
Opened 2024-12-20 07:44 UTC by amirRamirfatahi

#259 
# Pre-submission Checklist

> For tests to work you need a working neo4j and redis instance with the example dataset in `docker/db-graph`

- [*] **Testing**: Implement and pass new tests for the new features/fixes, `cargo test`.
- [ ] **Performance**: Ensure new code has relevant performance benchmarks, `cargo bench`

2025-01-01 22:37 UTC, SHAcollision requested changes
The proposed solution to this bug works. 

However, the solution is overly complex. Adding a new Hashmap to find Usernames by pubky_id does not seem necessary. This lookup table is not needed as we already have methods to retrieve a username of any user by its pubky_id. We already have `User:Details:{user_id}` keys that we can access with `UserDetails::get_by_id(pubky_id).username` . This is enough to figure what `username:pubky_id` (if any) we should remove from the sorted set.

2025-01-01 22:37 UTC, SHAcollision commented on src/models/user/search.rs
> +                Self::try_from_index_hashmap(&USER_NAME_HASHMAP_KEY_PARTS, user_id).await?;
Why not simply do `UserDetails::get_bt_id(user_id)` to figure what this user's current username (if any) is?

2025-01-01 22:42 UTC, SHAcollision commented on src/models/user/search.rs
> +        .await?;
Nice.

2025-01-01 22:43 UTC, SHAcollision commented on src/models/user/search.rs
> +            hashmap_items.push((user_id.0.clone(), username.clone()));
Not really needed, unless we can proof some sort of performance gain by maintaining this hashmap vs retrieving the usernames from the existing Redis JSON per user

2025-01-15 08:15 UTC, amirRamirfatahi commented on src/models/user/search.rs
> +                Self::try_from_index_hashmap(&USER_NAME_HASHMAP_KEY_PARTS, user_id).await?;
`UserDetails::get_bt_id(user_id)` will try to set the UserSearch index if it faces an index miss, leading to an infinite loop situation.  This will be a separate index that UserSearch itself is holding and maintaining, with no outer exposure, and it's precisely because we're performing the search like this.  
We can move the whole thing to a full text search index on the graph, which is my suggested way of doing search anyway. + it gives you a more sane searching experience by having things like fuzzy search.
For now, the extra hashmap seems to be worth it.

2025-01-16 02:19 UTC, amirRamirfatahi commented on src/models/user/search.rs
> +                Self::try_from_index_hashmap(&USER_NAME_HASHMAP_KEY_PARTS, user_id).await?;
`let user_details_list = UserDetails::get_from_index(keys).await?;` 
at this point the index and graph have both been updated. This requires its own storage to hold the previous username. We could do without anything extra if zrangebylex supported suffix searches, but it doesn't. We need to know which records are already there for the user id.  We can either use the hashmap, or use another in reverse for this query like `{id}:{username}`.  
I love the sentiment about being lean but this one hashmap (because of how we're doing search) is not going to haunt us.  
Again, the correct thing, is to have these searches on the graph db with a full_text search index on it and cache the most searched queries.

2025-01-16 11:33 UTC, SHAcollision commented on src/models/user/search.rs
> +                Self::try_from_index_hashmap(&USER_NAME_HASHMAP_KEY_PARTS, user_id).await?;
We are always doing `UserDetails::put_to_index()` after `UserSearch::put_to_index()`.

If you think we should do full text search, please open an issue for it, we discuss it.

2025-01-22 11:05 UTC, SHAcollision reviewed
Any idea why the Files tests are failing?

2025-01-22 11:05 UTC, SHAcollision commented on src/models/user/details.rs
> +        )),
I guess you figured something here. What was going on?

2025-01-22 11:05 UTC, SHAcollision commented on src/db/kv/index/json.rs
> +            None => Ok(None),
We might have been falling back to graph all this time?

2025-01-22 11:05 UTC, SHAcollision commented on src/db/kv/index/hashmap.rs
> +}
We can remove `src/db/kv/index/hashmap.rs` and the 2 new `traits.rs` methods from this PR, but add them to a new draft PR in case we need to use Redis HashMaps in the future.

2025-01-22 16:59 UTC, amirRamirfatahi commented on src/models/user/details.rs
> +        )),
links is an option, but if it was null in the DB, the deserialization was failing.

2025-01-22 17:00 UTC, amirRamirfatahi commented on src/db/kv/index/json.rs
> +            None => Ok(None),
Only those that had a failed deserialization, as we were failing silently.  
I don't think there were that many.

2025-01-22 17:01 UTC, amirRamirfatahi commented on src/db/kv/index/hashmap.rs
> +}
why though? I understand because it's not being used anywhere XD but still I don't think there's any harm in having it merged rn.

2025-01-22 18:46 UTC, SHAcollision commented on src/db/kv/index/hashmap.rs
> +}
We would need to review / test / mantain it. Better don't go through that until there is a need.

2025-01-22 23:35 UTC, SHAcollision approved these changes
Looks really good! Let's merge!

Thanks a lot @amirRamirfatahi not only for fixing the duplicated user search obvious bug, but most importantly for discovering a serialization bug and fixing it making the code safer (no silent failures on JSON errors), more consistent with standard Serde patterns, and fix an important bug in the user indexing logic :rocket:

2025-01-22 23:43 UTC, merged